---

- name: py36 | Check that py36 is still not installed
  become: true
  stat: path="{{ py36_bin }}"
  register: py36_already_installed
  ignore_errors: True

- name: py36 | Download
  get_url:
    url="{{ py36_url }}"
    dest="{{ py36_tar_file }}"
    checksum="md5:{{ py36_md5 }}"
  when: python_36 and py36_already_installed.stat.exists == false

- name: py36 | Uncompress
  unarchive:
    src={{ py36_tar_file }}
    dest=/tmp
    copy=no
    creates="{{ py36_sources }}"
  when: python_36 and py36_already_installed.stat.exists == false

- name: py36 | Compile and install
  become: true
  command: "{{ item }}"
  args:
    chdir: "{{ py36_sources }}"
  with_items:
    - "./configure --enable-optimizations --prefix {{ py36_install }}"
    - make
    - make install
  when: python_36 and py36_already_installed.stat.exists == false

- name: py36 | Create python_major_version symlink
  become: true
  file:
    src={{ py36_install }}
    dest='{{ base_install_folder }}/python{{ py36_major_version }}'
    state=link
  when: python_36 and py36_already_installed.stat.exists == false
