---

- name: py27 | Check that py27 is still not installed
  become: true
  stat: path="{{ py27_bin }}"
  register: py27_already_installed
  ignore_errors: True

- name: py27 | Download
  get_url:
    url="{{ py27_url }}"
    dest="{{ py27_tar_file }}"
    checksum="md5:{{ py27_md5 }}"
  when: python_27 and py27_already_installed.stat.exists == false

- name: py27 | Uncompress
  unarchive:
    src={{ py27_tar_file }}
    dest=/tmp
    copy=no
    creates="{{ py27_sources }}"
  when: python_27 and py27_already_installed.stat.exists == false

- name: py27 | Compile and install
  become: true
  command: "{{ item }}"
  args:
    chdir: "{{ py27_sources }}"
  with_items:
    - "./configure --enable-optimizations --prefix {{ py27_install }}"
    - make
    - make install
  when: python_27 and py27_already_installed.stat.exists == false

- name: py27 | Create python_major_version symlink
  become: true
  file:
    src={{ py27_install }}
    dest='{{ base_install_folder }}/python{{ py27_major_version }}'
    state=link
  when: python_27 and py27_already_installed.stat.exists == false
