---

- name: py35 | Check that py35 is still not installed
  become: true
  stat: path="{{ py35_bin }}"
  register: py35_already_installed
  ignore_errors: True

- name: py35 | Download
  get_url:
    url="{{ py35_url }}"
    dest="{{ py35_tar_file }}"
    checksum="md5:{{ py35_md5 }}"
  when: python_35 and py35_already_installed.stat.exists == false

- name: py35 | Uncompress
  unarchive:
    src={{ py35_tar_file }}
    dest=/tmp
    copy=no
    creates="{{ py35_sources }}"
  when: python_35 and py35_already_installed.stat.exists == false

- name: py35 | Compile and install
  become: true
  command: "{{ item }}"
  args:
    chdir: "{{ py35_sources }}"
  with_items:
    - "./configure --enable-optimizations --prefix {{ py35_install }}"
    - make
    - make install
  when: python_35 and py35_already_installed.stat.exists == false

- name: py35 | Create python_major_version symlink
  become: true
  file:
    src={{ py35_install }}
    dest='{{ base_install_folder }}/python{{ py35_major_version }}'
    state=link
  when: python_35 and py35_already_installed.stat.exists == false
