---

- name: py26 | Check that py26 is still not installed
  become: true
  stat: path="{{ py26_bin }}"
  register: py26_already_installed
  ignore_errors: True

- name: py26 | Download
  get_url:
    url="{{ py26_url }}"
    dest="{{ py26_tar_file }}"
    checksum="md5:{{ py26_md5 }}"
  when: python_26 and py26_already_installed.stat.exists == false

- name: py26 | Uncompress
  unarchive:
    src={{ py26_tar_file }}
    dest=/tmp
    copy=no
    creates="{{ py26_sources }}"
  when: python_26 and py26_already_installed.stat.exists == false

- name: py26 | Configure sources
  become: true
  command: "./configure --prefix {{ py26_install }}"
  args:
    chdir: "{{ py26_sources }}"
  when: python_26 and py26_already_installed.stat.exists == false

- name: py26 | Tweak sources
  become: true
  lineinfile:
    dest="{{ py26_sources }}/Modules/Setup"
    regexp=^#zlib(.*)
    line=zlib\1
    backrefs=yes
  when: python_26 and py26_already_installed.stat.exists == false

- name: py26 | Tweak sources
  become: true
  lineinfile:
    dest="{{ py26_sources }}/Modules/Setup"
    regexp=^#_sha256(.*)
    line=_sha256\1
    backrefs=yes
  when: python_26 and py26_already_installed.stat.exists == false

- name: py26 | Tweak sources
  become: true
  lineinfile:
    dest="{{ py26_sources }}/Modules/Setup"
    regexp=^#_sha512(.*)
    line=_sha512\1
    backrefs=yes
  when: python_26 and py26_already_installed.stat.exists == false

- name: py26 | Compile and install
  become: true
  command: "{{ item }}"
  args:
    chdir: "{{ py26_sources }}"
  with_items:
    - make
    - make install
  when: python_26 and py26_already_installed.stat.exists == false

- name: py26 | Create python_major_version symlink
  become: true
  file:
    src={{ py26_install }}
    dest='{{ base_install_folder }}/python{{ py26_major_version }}'
    state=link
  when: python_26 and py26_already_installed.stat.exists == false
